/* This is my copyright.*//* Watson */
/* Watson */
NAME = test/* Watson */
/* Watson */
SRC	=	AtmosphereRegulator.cpp		\/* Watson */
		Engine.cpp			\/* Watson */
		Errors.cpp			\/* Watson */
		Oxygenator.cpp			\/* Watson */
		RoverUnitTests.cpp		\/* Watson */
		WaterReclaimer.cpp/* Watson */
OBJ = $(SRC:.cpp=.o)/* Watson */
/* Watson */
CXX = g++/* Watson */
CXXFLAGS = -W -Wall -Wextra -std=c++14 -g/* Watson */
LDFLAGS =/* Watson */
/* Watson */
all: $(NAME)/* Watson */
/* Watson */
$(NAME): $(OBJ)/* Watson */
	$(CXX) -o $(NAME) $(OBJ) $(LDFLAGS)/* Watson */
/* Watson */
clean:/* Watson */
	$(RM) $(OBJ)/* Watson */
/* Watson */
fclean: clean/* Watson */
	$(RM) $(NAME)/* Watson */
/* Watson */
re: fclean all/* Watson */
/* Watson */
/* My own copyright */
